/** TODO when it's done, set BaseStatusId on Status table */
truncate table AclAuths       
Insert into AclAuths(InVisible, IsEditable, ObjectNameId, OID, PropertyNameId, RoleId, SystemRow, Version)            Select  InVisible, IsEditable, ObjectNameId, OID, PropertyNameId, RoleId, SystemRow, Version From itv913StandardUpgrade..AclAuths       
truncate table AclObjectNames       
Insert into AclObjectNames(Description, InVisible, Name, OID, SystemRow, Version)            Select  Description, InVisible, Name, OID, SystemRow, Version From itv913StandardUpgrade..AclObjectNames       
truncate table AclPasswordHistory       
Insert into AclPasswordHistory(CreatedBy, CreatedDate, EditedBy, EditedDate, OID, Password, PasswordChangedDate, UserId, Version)            Select  CreatedBy, CreatedDate, EditedBy, EditedDate, OID, Password, PasswordChangedDate, UserId, Version From itv913StandardUpgrade..AclPasswordHistory       
truncate table AclPropertyNames       
Insert into AclPropertyNames(Description, InVisible, Name, OID, SystemRow, Version)            Select  Description, InVisible, Name, OID, SystemRow, Version From itv913StandardUpgrade..AclPropertyNames       
truncate table AclRoles       
Insert into AclRoles(Description, InVisible, Name, OID, RoleType, SystemRow, Version)            Select  Description, InVisible, Name, OID, RoleType, SystemRow, Version From itv913StandardUpgrade..AclRoles       
truncate table AclXrefActionRole       
Insert into AclXrefActionRole(ActionId, InVisible, LimitAmount, OID, RoleId, Version)            Select  ActionId, InVisible, LimitAmount, OID, RoleId, Version From itv913StandardUpgrade..AclXrefActionRole       
truncate table AclXrefDoctypeRole       
Insert into AclXrefDoctypeRole(DocType, DocTypeId, InVisible, LimitAmount, OID, RoleId, Version)            Select  DocType, DocTypeId, InVisible, LimitAmount, OID, RoleId, Version From itv913StandardUpgrade..AclXrefDoctypeRole       
truncate table AclXrefFundRole       
Insert into AclXrefFundRole(FundId, OID, RoleId, Version)            Select  FundId, OID, RoleId, Version From itv913StandardUpgrade..AclXrefFundRole       
Set Identity_Insert [AclXrefPersonRole] On
truncate table AclXrefPersonRole       
Insert into AclXrefPersonRole(InVisible, OID, PersonId, RoleId, Version)            Select  InVisible, OID, PersonId, RoleId, Version From itv913StandardUpgrade..AclXrefPersonRole       
Set Identity_Insert [AclXrefPersonRole] Off
truncate table AclXrefReasonRole       
Insert into AclXrefReasonRole(InVisible, LimitAmount, OID, ReasonId, RoleId, Version)            Select  InVisible, LimitAmount, OID, ReasonId, RoleId, Version From itv913StandardUpgrade..AclXrefReasonRole       
truncate table AclXrefStatusRole       
Insert into AclXrefStatusRole(InVisible, LimitAmount, OID, RoleId, StatusId, Version)            Select  InVisible, LimitAmount, OID, RoleId, StatusId, Version From itv913StandardUpgrade..AclXrefStatusRole       
truncate table ActionReasons       
Insert into ActionReasons(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Source, SourceId, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Source, SourceId, Version From itv913StandardUpgrade..ActionReasons       
truncate table Actions       
Insert into Actions(ActionGroup, ActionType, ArStatusId, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, InVisible, Name, OID, OrgStatusId, RequireReason, RunProcessId, SystemRow, User1, User2, User3, User4, User5, User6, User7, User8, Version)            Select  ActionGroup, ActionType, ArStatusId, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, InVisible, Name, OID, OrgStatusId, RequireReason, RunProcessId, SystemRow, User1, User2, User3, User4, User5, User6, User7, User8, Version From itv913StandardUpgrade..Actions       
truncate table ActivityChoices       
Insert into ActivityChoices(Activity, Description)            Select  Activity, Description From itv913StandardUpgrade..ActivityChoices       
truncate table ActivityProfiles       
Insert into ActivityProfiles(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version From itv913StandardUpgrade..ActivityProfiles       
truncate table ActivityProfileSteps       
Insert into ActivityProfileSteps(CreatedBy, CreatedDate, DaysAfterPreviousStep, DoDocActionId, EditedBy, EditedDate, OID, PreviousStepsSuccessRequired, ProfileId, Step, TemplateId, Version)            Select  CreatedBy, CreatedDate, DaysAfterPreviousStep, DoDocActionId, EditedBy, EditedDate, OID, PreviousStepsSuccessRequired, ProfileId, Step, TemplateId, Version From itv913StandardUpgrade..ActivityProfileSteps       
truncate table ActivityTemplates       
Insert into ActivityTemplates(ActDate, Activity, ActTime, Alarm, AlarmBeforeType, AlarmTimeBefore, Comments, ContactId, ContactType, CreatedBy, CreatedDate, Duration, DurationType, EditedBy, EditedDate, ForOrgId, ForOrgType, ForOwnerType, ForUserId, ForUserType, HowCompleted, LetterDelivery, LetterTemplateId, LinkedTable, OID, OrgId, OrgType, OwnerType, Private, SchedAgainstMgr, SchedAgainstType, SchedForMgr, SchedForType, Subject, UserId, Version)            Select  ActDate, Activity, ActTime, Alarm, AlarmBeforeType, AlarmTimeBefore, Comments, ContactId, ContactType, CreatedBy, CreatedDate, Duration, DurationType, EditedBy, EditedDate, ForOrgId, ForOrgType, ForOwnerType, ForUserId, ForUserType, HowCompleted, LetterDelivery, LetterTemplateId, LinkedTable, OID, OrgId, OrgType, OwnerType, Private, SchedAgainstMgr, SchedAgainstType, SchedForMgr, SchedForType, Subject, UserId, Version From itv913StandardUpgrade..ActivityTemplates       
truncate table Activities       
Insert into Activities(ActDate, Activity, ActivityProfileId, ActTemplateId, ActTime, Alarm, AlarmBeforeType, AlarmTimeBefore, ArDocsAmount, ArDocsId, ArDocsRef, Comments, Completed, CompletedBy, CompletedDate, CompletedId, CompletedRecord, ContactId, CreatedBy, CreatedDate, Duration, DurationType, EditedBy, EditedDate, HowCompleted, LetterDelivery, LetterTemplateId, LinkedId, LinkedTable, MailStatus, MailStatusId, OID, OrgId, ParentActId, Priority, Queued, Source, SourceId, StepNbr, Subject, Success, Timeold, UserId, Version)            Select  ActDate, Activity, ActivityProfileId, ActTemplateId, ActTime, Alarm, AlarmBeforeType, AlarmTimeBefore, ArDocsAmount, ArDocsId, ArDocsRef, Comments, Completed, CompletedBy, CompletedDate, CompletedId, CompletedRecord, ContactId, CreatedBy, CreatedDate, Duration, DurationType, EditedBy, EditedDate, HowCompleted, LetterDelivery, LetterTemplateId, LinkedId, LinkedTable, MailStatus, MailStatusId, OID, OrgId, ParentActId, Priority, Queued, Source, SourceId, StepNbr, Subject, Success, Timeold, UserId, Version From itv913StandardUpgrade..Activities       
truncate table ActResults       
Insert into ActResults(ActComplete, ActSuccess, CreatedBy, CreatedDate, Description, DoDocActionId, EditedBy, EditedDate, ExpectFollowUp, InVisible, MustCodeAR, Name, OID, ResultType, RunProcessId, SystemRow, ValidFor, Version)            Select  ActComplete, ActSuccess, CreatedBy, CreatedDate, Description, DoDocActionId, EditedBy, EditedDate, ExpectFollowUp, InVisible, MustCodeAR, Name, OID, ResultType, RunProcessId, SystemRow, ValidFor, Version From itv913StandardUpgrade..ActResults       
truncate table Addresses       
Insert into Addresses(Address1, Address2, Address3, Address4, AddressType, City, Country, CreatedBy, CreatedDate, EditedBy, EditedDate, Name, OID, OrgId, PersonId, State, Territory, TimeZone, Version, ZipCode)            Select  Address1, Address2, Address3, Address4, AddressType, City, Country, CreatedBy, CreatedDate, EditedBy, EditedDate, Name, OID, OrgId, PersonId, State, Territory, TimeZone, Version, ZipCode From itv913StandardUpgrade..Addresses       
truncate table AddressTypes       
Insert into AddressTypes(Description, Name, OID, Version)            Select  Description, Name, OID, Version From itv913StandardUpgrade..AddressTypes       
truncate table ApiLayoutFields       
Insert into ApiLayoutFields(ApiLayoutRecId, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, FieldFormat, FieldFormula, FieldLength, FieldName, FieldSequence, IsIndicator, Name, OID, PositionEnd, PositionStart, TableName, Version)            Select  ApiLayoutRecId, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, FieldFormat, FieldFormula, FieldLength, FieldName, FieldSequence, IsIndicator, Name, OID, PositionEnd, PositionStart, TableName, Version From itv913StandardUpgrade..ApiLayoutFields       
truncate table ApiLayoutRecords       
Insert into ApiLayoutRecords(ApiLayoutId, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, RecordGroup, RecordSequence, RecordType, Version)            Select  ApiLayoutId, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, RecordGroup, RecordSequence, RecordType, Version From itv913StandardUpgrade..ApiLayoutRecords       
truncate table ApiLayouts       
Insert into ApiLayouts(CreatedBy, CreatedDate, Delimiter, Description, EditedBy, EditedDate, IsPreReconciled, LayoutFormat, LayoutType, Name, OID, ScanDirectory, Version)            Select  CreatedBy, CreatedDate, Delimiter, Description, EditedBy, EditedDate, IsPreReconciled, LayoutFormat, LayoutType, Name, OID, ScanDirectory, Version From itv913StandardUpgrade..ApiLayouts       
truncate table ArAdjust       
Insert into ArAdjust(AdjustedAmount, AdjustedArTranTypeId, AdjustedBatNbr, AdjustedCustId, AdjustedCustSourceId, AdjustedDiscAmt, AdjustedDocDate, AdjustedDocType, AdjustedOID, AdjustedRefNbr, AdjusterAmount, AdjusterArTranTypeId, AdjusterCustId, AdjusterCustSourceId, AdjusterDocDate, AdjusterDocType, AdjusterOID, AdjusterPerPost, AdjusterRefNbr, CreatedBy, CreatedByProg, CreatedDate, DateAdjusted, EditedBy, EditedByProg, EditedDate, GlAcct, GlBatchId, OID, PerAdjusted, PeriodToPost, PostedDate, Source, SourceId, User1, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User2, User20, User3, User4, User5, User6, User7, User8, User9, Version)            Select  AdjustedAmount, AdjustedArTranTypeId, AdjustedBatNbr, AdjustedCustId, AdjustedCustSourceId, AdjustedDiscAmt, AdjustedDocDate, AdjustedDocType, AdjustedOID, AdjustedRefNbr, AdjusterAmount, AdjusterArTranTypeId, AdjusterCustId, AdjusterCustSourceId, AdjusterDocDate, AdjusterDocType, AdjusterOID, AdjusterPerPost, AdjusterRefNbr, CreatedBy, CreatedByProg, CreatedDate, DateAdjusted, EditedBy, EditedByProg, EditedDate, GlAcct, GlBatchId, OID, PerAdjusted, PeriodToPost, PostedDate, Source, SourceId, User1, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User2, User20, User3, User4, User5, User6, User7, User8, User9, Version From itv913StandardUpgrade..ArAdjust       
truncate table ArBatch 
Insert into ArBatch(BatchDate, BusId, BusSourceId, CaSequence, CompanyId, ControlAmount, CorrectSelected, CreatedBy, CreatedDate, EditedBy, EditedDate, FileName, GlBatchId, GlDate, IsBalanced, IsCorrected, IsDeleted, IsEDI, IsPosted, LockBox, Name, OID, OrigBatchAmount, OrigBatchId, PeriodToPost, PostedDate, PostSelected, Source, SourceId, User1, User10, User2, User3, User4, User5, User6, User7, User8, User9, Version)            Select  BatchDate, BusId, BusSourceId, CaSequence, CompanyId, ControlAmount, CorrectSelected, CreatedBy, CreatedDate, EditedBy, EditedDate, FileName, GlBatchId, GlDate, IsBalanced, IsCorrected, IsDeleted, IsEDI, IsPosted, LockBox, Name, OID, OrigBatchAmount, OrigBatchId, PeriodToPost, PostedDate, PostSelected, Source, SourceId, User1, User10, User2, User3, User4, User5, User6, User7, User8, User9, Version From itv913StandardUpgrade..ArBatch            
truncate table ArDetailTypes 
Insert into ArDetailTypes(Category, CompanyId, CreatedBy, CreatedDate, EditedBy, EditedDate, GlAcct, Name, OID, SourceId, Version)            Select  Category, CompanyId, CreatedBy, CreatedDate, EditedBy, EditedDate, GlAcct, Name, OID, SourceId, Version From itv913StandardUpgrade..ArDetailTypes       
truncate table ArDocDetail       
Insert into ArDocDetail(Amount, ArDetailTypeId, Comments, CostPerUnit, CreatedBy, CreatedDate, Description, DiscAmount, DiscPercent, EditedBy, EditedDate, GlAcct, LinkedId, OID, OrderNum, POAmount, PODate, PONum, ProductId, ProductName, ProductSourceId, ProductUPC, ShipDate, Source, SourceId, Taxable, UnitPrice, Units, User1, User10, User11, User12, User2, User3, User4, User5, User6, User7, User8, User9, Version)            Select  Amount, ArDetailTypeId, Comments, CostPerUnit, CreatedBy, CreatedDate, Description, DiscAmount, DiscPercent, EditedBy, EditedDate, GlAcct, LinkedId, OID, OrderNum, POAmount, PODate, PONum, ProductId, ProductName, ProductSourceId, ProductUPC, ShipDate, Source, SourceId, Taxable, UnitPrice, Units, User1, User10, User11, User12, User2, User3, User4, User5, User6, User7, User8, User9, Version From itv913StandardUpgrade..ArDocDetail       
truncate table ArDocs       
Insert into ArDocs(ActionRsnId, Amount, ArBatchId, ArTermsId, ArTranTypeId, BOLNum, BrandId, BusId, BusSourceId, Closed, ClosedBy, ClosedDate, ClosedPeriod, Comments, CompanyId, CreatedBy, CreatedDate, CrossRefNum, Currency, CurrencyTypeId, CustId, CustSourceId, DiscAmount, DiscDate, DisputeAmount, DocDate, DocType, DueDate, EditedBy, EditedDate, ExchangeRate, ExchangeRateId, FactoryId, FactorySourceId, GlAcct, GlBatchId, LastNoteDate, OffsetId, OID, OrigAmount, OrigARDocId, OwnerId, PeriodToPost, PONum, PostedDate, ReasonChangeDate, ReasonId, Reconciled, RefNum, RmaNum, ShipToId, ShipToSourceId, SlsId, SlsSourceId, Source, SourceId, SplitFromOrigId, SplitFromParent, SrcChkNum, StatusChangeDate, StatusId, StoreNum, TermsCode, User1, User2, User3, User4, User5, User6, User7, Version)            Select  ActionRsnId, Amount, ArBatchId, ArTermsId, ArTranTypeId, BOLNum, BrandId, BusId, BusSourceId, Closed, ClosedBy, ClosedDate, ClosedPeriod, Comments, CompanyId, CreatedBy, CreatedDate, CrossRefNum, Currency, CurrencyTypeId, CustId, CustSourceId, DiscAmount, DiscDate, DisputeAmount, DocDate, DocType, DueDate, EditedBy, EditedDate, ExchangeRate, ExchangeRateId, FactoryId, FactorySourceId, GlAcct, GlBatchId, LastNoteDate, OffsetId, OID, OrigAmount, OrigARDocId, OwnerId, PeriodToPost, PONum, PostedDate, ReasonChangeDate, ReasonId, Reconciled, RefNum, RmaNum, ShipToId, ShipToSourceId, SlsId, SlsSourceId, Source, SourceId, SplitFromOrigId, SplitFromParent, SrcChkNum, StatusChangeDate, StatusId, StoreNum, TermsCode, User1, User2, User3, User4, User5, User6, User7, Version From itv913StandardUpgrade..ArDocs       
truncate table ArDocsExt       
Insert into ArDocsExt(ActsCount, BillToAttn, CaLinkedId, CaLinkedTable, CostCenter, CreatedBy, CreatedDate, CurrentPerAmount, DateGone, DateReentered, DCSourceId, EditedBy, EditedDate, ExportToTPMS, ExportTPMSBatchId, LastActDate, MasterDocAmount, MasterDocDate, MasterDocId, MasterDocType, NextActDate, NoteId, NotesCount, OID, OrderAmount, OrderDate, OrderNum, OrigRefNum, Owner2Id, Owner3Id, POAmount, PODate, PriorPerAmount, ProductGroup, ProductGroupId, ProjectNumber, ProNum, ReasonSubId, ReportingAmount, ReportingDisputeAmount, ReportingOrigAmount, SalesPerson, SalesPersonId, ShipToAttn, SrcChkAmount, SrcChkDate, SrcChkId, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User20, User8, User9, Version)            Select  ActsCount, BillToAttn, CaLinkedId, CaLinkedTable, CostCenter, CreatedBy, CreatedDate, CurrentPerAmount, DateGone, DateReentered, DCSourceId, EditedBy, EditedDate, ExportToTPMS, ExportTPMSBatchId, LastActDate, MasterDocAmount, MasterDocDate, MasterDocId, MasterDocType, NextActDate, NoteId, NotesCount, OID, OrderAmount, OrderDate, OrderNum, OrigRefNum, Owner2Id, Owner3Id, POAmount, PODate, PriorPerAmount, ProductGroup, ProductGroupId, ProjectNumber, ProNum, ReasonSubId, ReportingAmount, ReportingDisputeAmount, ReportingOrigAmount, SalesPerson, SalesPersonId, ShipToAttn, SrcChkAmount, SrcChkDate, SrcChkId, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User20, User8, User9, Version From itv913StandardUpgrade..ArDocsExt       
truncate table ArDocsAging       
Insert into ArDocsAging(Aging1, Aging10, Aging11, Aging12, Aging13, Aging14, Aging15, Aging16, Aging17, Aging18, Aging19, Aging2, Aging20, Aging3, Aging4, Aging5, Aging6, Aging7, Aging8, Aging9, AgingDescrip, AgingId, AgingName, Amount, CreatedBy, CreatedDate, DaysOld, EditedBy, EditedDate, OID, Version)            Select  Aging1, Aging10, Aging11, Aging12, Aging13, Aging14, Aging15, Aging16, Aging17, Aging18, Aging19, Aging2, Aging20, Aging3, Aging4, Aging5, Aging6, Aging7, Aging8, Aging9, AgingDescrip, AgingId, AgingName, Amount, CreatedBy, CreatedDate, DaysOld, EditedBy, EditedDate, OID, Version From itv913StandardUpgrade..ArDocsAging       
truncate table ArDocsMatch       
Insert into ArDocsMatch(CreatedBy, CreatedDate, CustId, EditedBy, EditedDate, Freight, Match1, Match10, Match11, Match12, Match13, Match14, Match15, Match16, Match17, Match18, Match19, Match2, Match20, Match3, Match4, Match5, Match6, Match7, Match8, Match9, NetAmount, OID, Reconciled, ReconciledDate, Surcharge, TaxCity, TaxCounty, TaxFed, TaxState, Version)            Select  CreatedBy, CreatedDate, CustId, EditedBy, EditedDate, Freight, Match1, Match10, Match11, Match12, Match13, Match14, Match15, Match16, Match17, Match18, Match19, Match2, Match20, Match3, Match4, Match5, Match6, Match7, Match8, Match9, NetAmount, OID, Reconciled, ReconciledDate, Surcharge, TaxCity, TaxCounty, TaxFed, TaxState, Version From itv913StandardUpgrade..ArDocsMatch       
truncate table ArRelatedTypes       
Insert into ArRelatedTypes(ArDocType, CanDelete, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version, ViewRoutine)            Select  ArDocType, CanDelete, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version, ViewRoutine From itv913StandardUpgrade..ArRelatedTypes       
truncate table ArSavedFilters       
Insert into ArSavedFilters(ActionReasonId, Amount, ArDocId, BOLNum, BusId, BusinessName, CarrierId, CarrierName, CarrierSourceID, Closed, ClosedEndDate, ClosedName, ClosedStartDate, Condish, ConfigReportMethod, ContactId, CreatedBy, CreatedDate, CrossRefNum, CurrencyTypeId, CustId, CustName, CustSourceId, DateType, DaysOldEnd, DaysOldStart, Department, Description, DocEndDate, DocStartDate, DocType, DueEndDate, DueStartDate, EditedBy, EditedDate, FactoryId, FactoryName, ForOwnerType, LinkedId, LinkedTable, ManagerId, Name, OffsetId, OID, OrgId, OrigAmount, OwnerId, ParentId, ParentName, ParentSourceId, PONum, ReasonChangeDate, ReasonChangeEndDate, ReasonChangeStartDate, ReasonGroup, ReasonGroupID, ReasonID, Reasons, RefFilterType, RefNum, ReportDesc, ReportFileName, ReportId, SlsId, SlsName, SlsSourceId, SrcChkNum, Status, StatusChangeEndDate, StatusChangeStartDate, Statusid, SysId, UserId, Version, Xml)            Select  ActionReasonId, Amount, ArDocId, BOLNum, BusId, BusinessName, CarrierId, CarrierName, CarrierSourceID, Closed, ClosedEndDate, ClosedName, ClosedStartDate, Condition, ConfigReportMethod, ContactId, CreatedBy, CreatedDate, CrossRefNum, CurrencyTypeId, CustId, CustName, CustSourceId, DateType, DaysOldEnd, DaysOldStart, Department, Description, DocEndDate, DocStartDate, DocType, DueEndDate, DueStartDate, EditedBy, EditedDate, FactoryId, FactoryName, ForOwnerType, LinkedId, LinkedTable, ManagerId, Name, OffsetId, OID, OrgId, OrigAmount, OwnerId, ParentId, ParentName, ParentSourceId, PONum, ReasonChangeDate, ReasonChangeEndDate, ReasonChangeStartDate, ReasonGroup, ReasonGroupID, ReasonID, Reasons, RefFilterType, RefNum, ReportDesc, ReportFileName, ReportId, SlsId, SlsName, SlsSourceId, SrcChkNum, Status, StatusChangeEndDate, StatusChangeStartDate, Statusid, SysId, UserId, Version, Xml From itv913StandardUpgrade..ArSavedFilters       
Set Identity_Insert [ArScoreCard] On
truncate table ArScoreCard       
Insert into ArScoreCard(Aging1, Aging10, Aging11, Aging12, Aging13, Aging14, Aging15, Aging16, Aging17, Aging18, Aging19, Aging2, Aging20, Aging3, Aging4, Aging5, Aging6, Aging7, Aging8, Aging9, AvgDaysBeyondTerms, AvgDaysToPay, BeginBalance, BestPossDaysToPay, BrokenPromisesAmount, BrokenPromisesCount, CEI, ClosedCredits, ClosedDebits, ClosedDeductions, ClosedDisputes, ClosedInvoices, ClosedPayments, ClosedPromises, CompanyId, CreatedBy, CreatedDate, CreditHoldId, CreditLimit, CreditLimit2, CreditRating, CreditScore, CreditStatus, CurrencyName, CurrencyTypeId, DDO, DiscAmount, DSO, DSOAD, DSOBP, EditedBy, EditedDate, ExchangeRate, ExchangeRateId, HighestBal, HighestBalPeriod, HitRate, LinkedId, LinkedTable, LinkedType, NewCredits, NewDebits, NewDeductions, NewDisputes, NewInvoices, NewPayments, NewPromises, OID, OpenCredits, OpenDebits, OpenDeductions, OpenDisputes, OpenInvoices, OpenPayments, OpenPromises, OrigAmount, OverDue, PeriodToPost, TotalClosed, TotalCount, TotalDue, TotalOpened, TotalOpenItems, Version, WeightedAvgDaysToPay, YtdCredits, YtdDebits, YtdDeductions, YtdDisputes, YtdInvoices, YtdPayments, YtdPromises, YTDSales)            Select  Aging1, Aging10, Aging11, Aging12, Aging13, Aging14, Aging15, Aging16, Aging17, Aging18, Aging19, Aging2, Aging20, Aging3, Aging4, Aging5, Aging6, Aging7, Aging8, Aging9, AvgDaysBeyondTerms, AvgDaysToPay, BeginBalance, BestPossDaysToPay, BrokenPromisesAmount, BrokenPromisesCount, CEI, ClosedCredits, ClosedDebits, ClosedDeductions, ClosedDisputes, ClosedInvoices, ClosedPayments, ClosedPromises, CompanyId, CreatedBy, CreatedDate, CreditHoldId, CreditLimit, CreditLimit2, CreditRating, CreditScore, CreditStatus, CurrencyName, CurrencyTypeId, DDO, DiscAmount, DSO, DSOAD, DSOBP, EditedBy, EditedDate, ExchangeRate, ExchangeRateId, HighestBal, HighestBalPeriod, HitRate, LinkedId, LinkedTable, LinkedType, NewCredits, NewDebits, NewDeductions, NewDisputes, NewInvoices, NewPayments, NewPromises, OID, OpenCredits, OpenDebits, OpenDeductions, OpenDisputes, OpenInvoices, OpenPayments, OpenPromises, OrigAmount, OverDue, PeriodToPost, TotalClosed, TotalCount, TotalDue, TotalOpened, TotalOpenItems, Version, WeightedAvgDaysToPay, YtdCredits, YtdDebits, YtdDeductions, YtdDisputes, YtdInvoices, YtdPayments, YtdPromises, YTDSales From itv913StandardUpgrade..ArScoreCard       
Set Identity_Insert [ArScoreCard] Off
truncate table ArTerms       
Insert into ArTerms(CompanyId, CreatedBy, CreatedDate, Description, DiscountDays, DiscountPercent, DueInDays, EditedBy, EditedDate, Name, OID, Version)            Select  CompanyId, CreatedBy, CreatedDate, Description, DiscountDays, DiscountPercent, DueInDays, EditedBy, EditedDate, Name, OID, Version From itv913StandardUpgrade..ArTerms       
truncate table Attachments       
Insert into Attachments(AttachmentTypeId, Comments, CreatedBy, CreatedDate, EditedBy, EditedDate, LinkedId, LinkedTable, Location, MimeType, Name, OID, Source, SourceId, Version)            Select  AttachmentTypeId, Comments, CreatedBy, CreatedDate, EditedBy, EditedDate, LinkedId, LinkedTable, Location, MimeType, Name, OID, Source, SourceId, Version From itv913StandardUpgrade..Attachments       
truncate table ArTranTypes       
Insert into ArTranTypes(CompanyId, CreatedBy, CreatedDate, Description, DocType, EditedBy, EditedDate, GlAcct, GlAcctDesc, GlDetailAcct, GlDetailAcctDesc, IsOpposingTran, MovedArTranTypeId, Multiplier, Name, NewRefnumGeneratorId, OID, OpposingName, Source, SourceId, UseReasonGL, Version)            Select  CompanyId, CreatedBy, CreatedDate, Description, DocType, EditedBy, EditedDate, GlAcct, GlAcctDesc, GlDetailAcct, GlDetailAcctDesc, IsOpposingTran, MovedArTranTypeId, Multiplier, Name, NewRefnumGeneratorId, OID, OpposingName, Source, SourceId, UseReasonGL, Version From itv913StandardUpgrade..ArTranTypes       
truncate table AttachmentTypes       
Insert into AttachmentTypes(ArDocType, CanDelete, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version, ViewRoutine)            Select  ArDocType, CanDelete, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version, ViewRoutine From itv913StandardUpgrade..AttachmentTypes       
truncate table CfgAging       
Insert into CfgAging(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, EndDay, IsUsed, Name, OID, StartDay, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, EndDay, IsUsed, Name, OID, StartDay, Version From itv913StandardUpgrade..CfgAging       
truncate table CfgUsers       
Insert into CfgUsers(CompanyId, CreatedBy, CreatedDate, DealApprovalLimit, Description, EditedBy, EditedDate, Email, Email2, InActive, InVisible, IsAdmin, IsBasic, IsGuest, IsManager, IsOwner, IsSuperUser, LName, Login, ManagerId, Name, OID, Password, PasswordChangedDate, PersonId, PromoApprovalLimit, Source, SourceId, UserType, Version)            Select  CompanyId, CreatedBy, CreatedDate, DealApprovalLimit, Description, EditedBy, EditedDate, Email, Email2, InActive, InVisible, IsAdmin, IsBasic, IsGuest, IsManager, IsOwner, IsSuperUser, LName, Login, ManagerId, Name, OID, Password, PasswordChangedDate, PersonId, PromoApprovalLimit, Source, SourceId, UserType, Version From itv913StandardUpgrade..CfgUsers       
truncate table CorAlgorithms       
Insert into CorAlgorithms(AlgorithmType, AllowShortPay, Application, Category, CorSetupGroupId, CreatedBy, CreatedDate, DefaultValue, Description, EditedBy, EditedDate, GroupId, InActive, OID, Value, ValueType, Variable, Version)            Select  AlgorithmType, AllowShortPay, Application, Category, CorSetupGroupId, CreatedBy, CreatedDate, DefaultValue, Description, EditedBy, EditedDate, GroupId, InActive, OID, Value, ValueType, Variable, Version From itv913StandardUpgrade..CorAlgorithms       
truncate table CorCodes       
Insert into CorCodes(ArTranType, CorCodeType, CorCodeTypeDesc, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, ReasonId, Version)            Select  ArTranType, CorCodeType, CorCodeTypeDesc, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, ReasonId, Version From itv913StandardUpgrade..CorCodes       
truncate table CorOffsetTolerance
INSERT INTO CorOffsetTolerance (OID ,Version,CreatedBy,CreatedDate,CreditArTranTypeId,CreditReasonId,DebitArTranTypeId,DebitReasonId ,EditedBy,EditedDate,GroupId) SELECT OID ,Version,CreatedBy,CreatedDate,CreditArTranTypeId,CreditReasonId,DebitArTranTypeId,DebitReasonId ,EditedBy,EditedDate,GroupId from ITV913StandardUpgrade..OffsetTolerance
truncate table CorReasonClearing       
Insert into CorReasonClearing(CreatedBy, CreatedDate, EditedBy, EditedDate, GroupId, OID, ReasonId, TolOver, TolOverReasonId, TolOverTranTypeId, TolUnder, TolUnderReasonId, TolUnderTranTypeId, Version)            Select  CreatedBy, CreatedDate, EditedBy, EditedDate, GroupId, OID, ReasonId, TolOver, TolOverReasonId, TolOverTranTypeId, TolUnder, TolUnderReasonId, TolUnderTranTypeId, Version From itv913StandardUpgrade..CorReasonClearing       
truncate table CorReasonTolerance       
Insert into CorReasonTolerance(CreatedBy, CreatedDate, CustGroupId, EditedBy, EditedDate, NewReasonId, NewTranTypeId, OID, ReasonId, TolAmount, Version)            Select  CreatedBy, CreatedDate, CustGroupId, EditedBy, EditedDate, NewReasonId, NewTranTypeId, OID, ReasonId, TolAmount, Version From itv913StandardUpgrade..CorReasonTolerance       
truncate table CorResults       
Insert into CorResults(CorCodeId, CreatedBy, CreatedDate, EditedBy, EditedDate, LinkedId, LinkedTable, OID, Version)            Select  CorCodeId, CreatedBy, CreatedDate, EditedBy, EditedDate, LinkedId, LinkedTable, OID, Version From itv913StandardUpgrade..CorResults       
truncate table CorSetupDisc       
Insert into CorSetupDisc(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, GroupId, OID, Value, Variable, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, GroupId, OID, Value, Variable, Version From itv913StandardUpgrade..CorSetupDisc       
truncate table CorSetupGlobal       
Insert into CorSetupGlobal(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, OID, Value, Variable, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, OID, Value, Variable, Version From itv913StandardUpgrade..CorSetupGlobal       
truncate table CorSetupGroups       
Insert into CorSetupGroups(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, GroupType, InActive, Name, OID, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, GroupType, InActive, Name, OID, Version From itv913StandardUpgrade..CorSetupGroups       
truncate table CorSetupMatch       
Insert into CorSetupMatch(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, GroupId, OID, Value, Variable, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, GroupId, OID, Value, Variable, Version From itv913StandardUpgrade..CorSetupMatch       
truncate table CorSetupMemo       
Insert into CorSetupMemo(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, GroupId, OID, Value, Variable, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, GroupId, OID, Value, Variable, Version From itv913StandardUpgrade..CorSetupMemo       
truncate table CorSetupOffset       
Insert into CorSetupOffset(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, GroupId, OID, Value, Variable, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, GroupId, OID, Value, Variable, Version From itv913StandardUpgrade..CorSetupOffset       
truncate table CreditClasses       
Insert into CreditClasses(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version From itv913StandardUpgrade..CreditClasses       
truncate table CreditData       
Insert into CreditData(AttachmentId, Bit1, Bit2, Bit3, Bit4, Char01, Char02, Char03, Char04, Char05, Char06, Char07, Char08, Char09, Char10, Char11, Char12, CreatedBy, CreatedDate, CreditLimit, CreditScore, CreditSummaryId, Date1, Date2, Date3, Date4, Date5, Date6, Date7, Date8, EditedBy, EditedDate, IntF1, IntF2, IntF3, IntF4, IntF5, IntF6, IntF7, IntF8, Money1, Money2, Money3, Money4, Money5, Money6, Money7, Money8, OID, OrderDate, OrgId, Ratio1, Ratio2, Ratio3, Ratio4, Ratio5, Ratio6, Ratio7, Ratio8, Source, SourceId, Version)            Select  AttachmentId, Bit1, Bit2, Bit3, Bit4, Char01, Char02, Char03, Char04, Char05, Char06, Char07, Char08, Char09, Char10, Char11, Char12, CreatedBy, CreatedDate, CreditLimit, CreditScore, CreditSummaryId, Date1, Date2, Date3, Date4, Date5, Date6, Date7, Date8, EditedBy, EditedDate, IntF1, IntF2, IntF3, IntF4, IntF5, IntF6, IntF7, IntF8, Money1, Money2, Money3, Money4, Money5, Money6, Money7, Money8, OID, OrderDate, OrgId, Ratio1, Ratio2, Ratio3, Ratio4, Ratio5, Ratio6, Ratio7, Ratio8, Source, SourceId, Version From itv913StandardUpgrade..CreditData       
truncate table CreditHold       
Insert into CreditHold(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Inactive, InVisible, IsOnHold, Name, OID, Source, SourceId, SystemRow, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Inactive, InVisible, IsOnHold, Name, OID, Source, SourceId, SystemRow, Version From itv913StandardUpgrade..CreditHold       
truncate table CreditRisk       
Insert into CreditRisk(CreatedBy, CreatedDate, CreditClassId, CreditLimit, Description, EditedBy, EditedDate, MaxCreditScore, MinCreditScore, Name, OID, Version)            Select  CreatedBy, CreatedDate, CreditClassId, CreditLimit, Description, EditedBy, EditedDate, MaxCreditScore, MinCreditScore, Name, OID, Version From itv913StandardUpgrade..CreditRisk       
truncate table CreditRules       
Insert into CreditRules(ColumnName, CreatedBy, CreatedDate, CreditClassId, DataSource, Description, EditedBy, EditedDate, Name, OID, Operation, SelectionMode, Version, Weight)            Select  ColumnName, CreatedBy, CreatedDate, CreditClassId, DataSource, Description, EditedBy, EditedDate, Name, OID, Operation, SelectionMode, Version, Weight From itv913StandardUpgrade..CreditRules       
truncate table CreditSummary       
Insert into CreditSummary(Approved, ApprovedBy, ApprovedDate, Bit1, Bit2, Char01, Char02, Char03, Char04, Comments, CreatedBy, CreatedDate, CreditClassId, CreditInfoSource, CreditLimitAmount, CreditLimitDate, CreditManagerId, CreditReviewDate, CreditReviewDays, CreditReviewNextDate, CreditRiskId, CreditScore, Date1, Date2, EditedBy, EditedDate, FirstInvoiceDate, HighCreditAmount, HighCreditDate, IntF1, IntF2, IntF3, IntF4, LastInvoiceDate, Money1, Money2, Money3, Money4, OID, OrgId, Ratio1, Ratio2, Ratio3, Ratio4, Version)            Select  Approved, ApprovedBy, ApprovedDate, Bit1, Bit2, Char01, Char02, Char03, Char04, Comments, CreatedBy, CreatedDate, CreditClassId, CreditInfoSource, CreditLimitAmount, CreditLimitDate, CreditManagerId, CreditReviewDate, CreditReviewDays, CreditReviewNextDate, CreditRiskId, CreditScore, Date1, Date2, EditedBy, EditedDate, FirstInvoiceDate, HighCreditAmount, HighCreditDate, IntF1, IntF2, IntF3, IntF4, LastInvoiceDate, Money1, Money2, Money3, Money4, OID, OrgId, Ratio1, Ratio2, Ratio3, Ratio4, Version From itv913StandardUpgrade..CreditSummary       
truncate table CreditSummaryDetail       
Insert into CreditSummaryDetail(CalcVal, ColumnName, CreatedBy, CreatedDate, CreditRuleId, CreditSummaryId, EditedBy, EditedDate, LastCalc, LastSrc, OID, Operation, Source, SrcVal, Version, Weight)            Select  CalcVal, ColumnName, CreatedBy, CreatedDate, CreditRuleId, CreditSummaryId, EditedBy, EditedDate, LastCalc, LastSrc, OID, Operation, Source, SrcVal, Version, Weight From itv913StandardUpgrade..CreditSummaryDetail       
truncate table CreditSummaryXref       
Insert into CreditSummaryXref(CreditDataId, CreditSummaryDetailId, CreditSummaryId, OID, Version)            Select  CreditDataId, CreditSummaryDetailId, CreditSummaryId, OID, Version From itv913StandardUpgrade..CreditSummaryXref       
truncate table CurrencyTypes       
Insert into CurrencyTypes(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Source, SourceId, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Source, SourceId, Version From itv913StandardUpgrade..CurrencyTypes       
truncate table Custom1       
Insert into Custom1(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, LinkedCol, LinkedId, LinkedTable, Name, OID, User01, User02, User03, User04, User05, User06, User07, User08, User09, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User20, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, LinkedCol, LinkedId, LinkedTable, Name, OID, User01, User02, User03, User04, User05, User06, User07, User08, User09, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User20, Version From itv913StandardUpgrade..Custom1       
truncate table Custom2       
Insert into Custom2(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, LinkedCol, LinkedId, LinkedTable, Name, OID, User01, User02, User03, User04, User05, User06, User07, User08, User09, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User20, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, LinkedCol, LinkedId, LinkedTable, Name, OID, User01, User02, User03, User04, User05, User06, User07, User08, User09, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User20, Version From itv913StandardUpgrade..Custom2       
truncate table Custom3       
Insert into Custom3(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, LinkedCol, LinkedId, LinkedTable, Name, OID, User01, User02, User03, User04, User05, User06, User07, User08, User09, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User20, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, LinkedCol, LinkedId, LinkedTable, Name, OID, User01, User02, User03, User04, User05, User06, User07, User08, User09, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User20, Version From itv913StandardUpgrade..Custom3       
truncate table Custom4       
Insert into Custom4(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, LinkedCol, LinkedId, LinkedTable, Name, OID, User01, User02, User03, User04, User05, User06, User07, User08, User09, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User20, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, LinkedCol, LinkedId, LinkedTable, Name, OID, User01, User02, User03, User04, User05, User06, User07, User08, User09, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User20, Version From itv913StandardUpgrade..Custom4       
truncate table EntityProps       
Insert into EntityProps(Alignment, Caption, ColumnName, CreatedBy, CreatedDate, DefaultValue, DisplayMaskId, Editable, EditedBy, EditedDate, EntityId, EntityName, IsRequired, OID, OrderForForm, OrderForMassUpdate, OrderForQuickEntry, OrderForSearch, Ordinal, RoleId, ScreenName, SearchType, TrackHistory, UserId, UserLevelEditable, UserLevelForm, UserLevelMassUpdate, UserLevelQuickEntry, UserLevelSave, UserLevelSearch, UserLevelVisible, Version, ViewId, Visible, Width)            Select  Alignment, Caption, ColumnName, CreatedBy, CreatedDate, DefaultValue, DisplayMaskId, Editable, EditedBy, EditedDate, EntityId, EntityName, IsRequired, OID, OrderForForm, OrderForMassUpdate, OrderForQuickEntry, OrderForSearch, Ordinal, RoleId, ScreenName, SearchType, TrackHistory, UserId, UserLevelEditable, UserLevelForm, UserLevelMassUpdate, UserLevelQuickEntry, UserLevelSave, UserLevelSearch, UserLevelVisible, Version, ViewId, Visible, Width From itv913StandardUpgrade..EntityProps       
truncate table ExchangeRates       
Insert into ExchangeRates(CurrencyTypeId, ExchangeDate, OID, PeriodToPost, Rate, Version)            Select  CurrencyTypeId, ExchangeDate, OID, PeriodToPost, Rate, Version From itv913StandardUpgrade..ExchangeRates       
Set Identity_Insert [ExportTranResults] On
truncate table ExportTranResults       
Insert into ExportTranResults(CHECK_BATCH_TIME, CHK_CHECK_Id, CHK_CHECK_NBR, CHK_SEQ_NBR, CUSTAR_NBR, DEP_RECORD_Id, ERROR_CODE, ERROR_MSG, INV_INVOICE_NBR, OID)            Select  CHECK_BATCH_TIME, CHK_CHECK_Id, CHK_CHECK_NBR, CHK_SEQ_NBR, CUSTAR_NBR, DEP_RECORD_Id, ERROR_CODE, ERROR_MSG, INV_INVOICE_NBR, OID From itv913StandardUpgrade..ExportTranResults       
Set Identity_Insert [ExportTranResults] Off
truncate table GlAdjustments       
Insert into GlAdjustments(ArDocId, CreatedBy, CreatedDate, CreditAmount, DebitAmount, EditedBy, EditedDate, GlAcct, GlBatchId, LinkedId, LinkedTable, OID, Segment1, Segment2, Segment3, Segment4, Segment5, Segment6, Segment7, Segment8, Segment9, Version)            Select  ArDocId, CreatedBy, CreatedDate, CreditAmount, DebitAmount, EditedBy, EditedDate, GlAcct, GlBatchId, LinkedId, LinkedTable, OID, Segment1, Segment2, Segment3, Segment4, Segment5, Segment6, Segment7, Segment8, Segment9, Version From itv913StandardUpgrade..GlAdjustments       
Set Identity_Insert [GlBatch] On
truncate table GlBatch       
Insert into GlBatch(BatchStatusId, CompanyId, CreatedBy, CreatedDate, EditedBy, EditedDate, ExitCode, ExitDate, Description, FilterBusId, FilterDocBegin, FilterDocEnd, FilterSource, OID, PeriodToPost, PostedDate, Success, Version)            Select  BatchStatusId, CompanyId, CreatedBy, CreatedDate, EditedBy, EditedDate, ExitCode, ExitDate, ExitMessage, FilterBusId, FilterDocBegin, FilterDocEnd, FilterSource, OID, PeriodToPost, PostedDate, Success, Version From itv913StandardUpgrade..GlBatch       
Set Identity_Insert [GlBatch] Off
Set Identity_Insert [GlDistribution] On
truncate table GlDistribution       
Insert into GlDistribution(ArDocId, CreatedBy, CreatedDate, CreditAmount, DebitAmount, EditedBy, EditedDate, GlAcct, GlBatchId, LinkedId, LinkedTable, OID, Segment1, Segment2, Segment3, Segment4, Segment5, Segment6, Segment7, Segment8, Segment9, Version)            Select  ArDocId, CreatedBy, CreatedDate, CreditAmount, DebitAmount, EditedBy, EditedDate, GlAcct, GlBatchId, LinkedId, LinkedTable, OID, Segment1, Segment2, Segment3, Segment4, Segment5, Segment6, Segment7, Segment8, Segment9, Version From itv913StandardUpgrade..GlDistribution       
Set Identity_Insert [GlDistribution] Off
truncate table GlDistributionHistory       
Insert into GlDistributionHistory(ArDocId, CreatedBy, CreatedDate, CreditAmount, DebitAmount, EditedBy, EditedDate, GlAcct, GlBatchId, LinkedId, LinkedTable, OID, Segment1, Segment2, Segment3, Segment4, Segment5, Segment6, Segment7, Segment8, Segment9, Version)            Select  ArDocId, CreatedBy, CreatedDate, CreditAmount, DebitAmount, EditedBy, EditedDate, GlAcct, GlBatchId, LinkedId, LinkedTable, OID, Segment1, Segment2, Segment3, Segment4, Segment5, Segment6, Segment7, Segment8, Segment9, Version From itv913StandardUpgrade..GlDistributionHistory       
Set Identity_Insert [History] On
truncate table History       
Insert into History(Caption, ColumnName, EditedBy, EditedByName, EditedDate, EditedPeriod, LinkedId, LinkedTable, NewValue, NewValueName, OID, OldValue, OldValueName, Version)            Select  Caption, ColumnName, EditedBy, EditedByName, EditedDate, EditedPeriod, LinkedId, LinkedTable, NewValue, NewValueName, OID, OldValue, OldValueName, Version From itv913StandardUpgrade..History       
Set Identity_Insert [History] Off
truncate table LetterDeliveryTypes       
Insert into LetterDeliveryTypes(ConfirmationRequired, DeliveryType, Description, ForActivities, ForActivityTemplates, IsEmailReqd, IsFaxReqd)            Select  ConfirmationRequired, DeliveryType, Description, ForActivities, ForActivityTemplates, IsEmailReqd, IsFaxReqd From itv913StandardUpgrade..LetterDeliveryTypes       
truncate table LetterTemplates       
Insert into LetterTemplates(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, ReportId, URL, UseReport, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, ReportId, URL, UseReport, Version From itv913StandardUpgrade..LetterTemplates       
truncate table LockBox       
Insert into LockBox(AccountType, ArSystem, ArTranTypeId, BankName, BankNumber, BusId, CompanyId, CreatedBy, CreatedDate, EditedBy, EditedDate, IsCross, IsDefault, IsTransfer, Location, LockBoxNumber, OID, User1, User2, User3, User4, User5, Version)            Select  AccountType, ArSystem, ArTranTypeId, BankName, BankNumber, BusId, CompanyId, CreatedBy, CreatedDate, EditedBy, EditedDate, IsCross, IsDefault, IsTransfer, Location, LockBoxNumber, OID, User1, User2, User3, User4, User5, Version From itv913StandardUpgrade..LockBox       
truncate table NewObjectId       
Insert into NewObjectId(KeyName, NextId)            Select  KeyName, NextId From itv913StandardUpgrade..NewObjectId       
truncate table NewRefnumGenerator       
Insert into NewRefnumGenerator(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, KeyName, NextId, OID, Prefix, RangeMax, RangeMin, Suffix, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, KeyName, NextId, OID, Prefix, RangeMax, RangeMin, Suffix, Version From itv913StandardUpgrade..NewRefnumGenerator       
truncate table Notes       
Insert into Notes(ActivityId, CreatedBy, CreatedDate, EditedBy, EditedDate, LinkedId, LinkedTable, Note, OID, Sequence, Source, SourceId, TypeId, Version, Visible, Void)            Select  ActivityId, CreatedBy, CreatedDate, EditedBy, EditedDate, LinkedId, LinkedTable, Note, OID, Sequence, Source, SourceId, TypeId, Version, Visible, Void From itv913StandardUpgrade..Notes       
truncate table Orgs       
Insert into Orgs(Address1, Address2, Address3, Address4, ArTermsId, BusId, City, CommentOwner, Comments, CompanyId, Country, CreatedBy, CreatedDate, Currency, CurrencyTypeId, CustClassId, DefaultOwnerId, DefaultPersonId, DefaultSlsId, EditedBy, EditedDate, Fax, FaxExt, FaxId, GlAcct, InActive, InVisible, Name, Name2, OID, OrgsStatusId, OrgType, ParentId, Phone, Phone2, Phone2Ext, PhoneExt, PrimaryAddressId, Source, SourceId, State, Territory, TimeZone, TimeZoneID, Version, Website, ZipCode)            Select  Address1, Address2, Address3, Address4, ArTermsId, BusId, City, CommentOwner, Comments, CompanyId, Country, CreatedBy, CreatedDate, Currency, CurrencyTypeId, CustClassId, DefaultOwnerId, DefaultPersonId, DefaultSlsId, EditedBy, EditedDate, Fax, FaxExt, FaxId, GlAcct, InActive, InVisible, Name, Name2, OID, OrgsStatusId, OrgType, ParentId, Phone, Phone2, Phone2Ext, PhoneExt, PrimaryAddressId, Source, SourceId, State, Territory, TimeZone, TimeZoneID, Version, Website, ZipCode From itv913StandardUpgrade..Orgs       
truncate table OrgsCalc       
Insert into OrgsCalc(Aging1, Aging10, Aging11, Aging12, Aging13, Aging14, Aging15, Aging16, Aging17, Aging18, Aging19, Aging2, Aging20, Aging3, Aging4, Aging5, Aging6, Aging7, Aging8, Aging9, AvgDaysBeyondTerms, AvgDaysToPay, BestPossDaysToPay, CreatedBy, CreatedDate, CurrentPerAmount, DateOfLastCash, DSO1, DSO2, EditedBy, EditedDate, HighestBal, OID, OpenCredits, OpenPromises, OrgId, OverDue, PriorPerAmount, TotalDue, TotalOpenItems, Version, WeightedAvgDaysToPay, YTDSales)            Select  Aging1, Aging10, Aging11, Aging12, Aging13, Aging14, Aging15, Aging16, Aging17, Aging18, Aging19, Aging2, Aging20, Aging3, Aging4, Aging5, Aging6, Aging7, Aging8, Aging9, AvgDaysBeyondTerms, AvgDaysToPay, BestPossDaysToPay, CreatedBy, CreatedDate, CurrentPerAmount, DateOfLastCash, DSO1, DSO2, EditedBy, EditedDate, HighestBal, OID, OpenCredits, OpenPromises, OID, OverDue, PriorPerAmount, TotalDue, TotalOpenItems, Version, WeightedAvgDaysToPay, YTDSales From itv913StandardUpgrade..OrgsCalc       
truncate table OrgsExt       
Insert into OrgsExt(CanReceiveEmail, CanReceiveFax, CorDiscountGroupId, CorMatchGroupId, CorMemoGroupId, CorOffsetGroupId, CorpGuarantee, CorpGuarExpDate, CreatedBy, CreatedDate, CreditApp, CreditClassId, CreditHoldId, CreditLimit, CreditLimit2, CreditRating, CreditScore, CreditStatus, DefaultFactoryId, DefaultOwner2Id, DefaultOwner3Id, DefaultRegionId, DIPDate, DIPNum, DivisionId, Duns, EditedBy, EditedDate, FreightTerms, GLN, Is850, LastActBy, LastActDate, LastActId, LastDocDate, LastNoteBy, LastNoteDate, LastNoteId, LCExpDate, NextActDate, NextActId, OID, OrgClass1Id, OrgClass2Id, OrgClass3Id, OrgId, PayFromId, RemovedDate, SetupDate, Sic, TaxpayerId, TermsCode, UCCExpDate, User1, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User2, User20, User3, User4, User5, User6, User7, User8, User9, Version, Website)            Select  CanReceiveEmail, CanReceiveFax, CorDiscountGroupId, CorMatchGroupId, CorMemoGroupId, CorOffsetGroupId, CorpGuarantee, CorpGuarExpDate, CreatedBy, CreatedDate, CreditApp, CreditClassId, CreditHoldId, CreditLimit, CreditLimit2, CreditRating, CreditScore, CreditStatus, DefaultFactoryId, DefaultOwner2Id, DefaultOwner3Id, DefaultRegionId, DIPDate, DIPNum, DivisionId, Duns, EditedBy, EditedDate, FreightTerms, GLN, Is850, LastActBy, LastActDate, LastActId, LastDocDate, LastNoteBy, LastNoteDate, LastNoteId, LCExpDate, NextActDate, NextActId, OID, OrgClass1Id, OrgClass2Id, OrgClass3Id, OID, PayFromId, RemovedDate, SetupDate, Sic, TaxpayerId, TermsCode, UCCExpDate, User1, User10, User11, User12, User13, User14, User15, User16, User17, User18, User19, User2, User20, User3, User4, User5, User6, User7, User8, User9, Version, Website From itv913StandardUpgrade..OrgsExt       
truncate table OrgsSavedFilters       
Insert into OrgsSavedFilters(Aging1, Aging10, Aging2, Aging3, Aging4, Aging5, Aging6, Aging7, Aging8, Aging9, BusId, BusinessName, CompanyId, CompanyName, Condish, ConfigReportMethod, CreatedBy, CreatedDate, Description, DocType, EditedBy, EditedDate, EndActDate, EndNoteDate, InActive, LinkedId, LinkedTable, Name, NameBetween, NameEnd, NameStart, OID, OrgType, OrgTypeName, OwnerId, OwnerName, Phone, ReportFileName, ReportId, Reports, SlsId, SlsName, SlsSourceId, SourceId, StartActDate, StartNoteDate, SystemId, TotalDue, TotalOpenItems, UserId, Version, Xml)            Select  Aging1, Aging10, Aging2, Aging3, Aging4, Aging5, Aging6, Aging7, Aging8, Aging9, BusId, BusinessName, CompanyId, CompanyName, Condition, ConfigReportMethod, CreatedBy, CreatedDate, Description, DocType, EditedBy, EditedDate, EndActDate, EndNoteDate, InActive, LinkedId, LinkedTable, Name, NameBetween, NameEnd, NameStart, OID, OrgType, OrgTypeName, OwnerId, OwnerName, Phone, ReportFileName, ReportId, Reports, SlsId, SlsName, SlsSourceId, SourceId, StartActDate, StartNoteDate, SystemId, TotalDue, TotalOpenItems, UserId, Version, Xml From itv913StandardUpgrade..OrgsSavedFilters       
truncate table OrgsClasses       
Insert into OrgsClasses(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Source, SourceId, ValidFor, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Source, SourceId, ValidFor, Version From itv913StandardUpgrade..OrgsClasses       
truncate table OrgsMICR       
Insert into OrgsMICR(AccountName, AccountNum, BankName, CreatedBy, CreatedDate, EditedBy, EditedDate, OID, OrgId, RoutingNum, Source, SourceId, User1, User2, User3, Version)            Select  AccountName, AccountNum, BankName, CreatedBy, CreatedDate, EditedBy, EditedDate, OID, OrgId, RoutingNum, Source, SourceId, User1, User2, User3, Version From itv913StandardUpgrade..OrgsMICR       
truncate table OrgsStatus       
Insert into OrgsStatus(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, InActive, InVisible, Name, OID, SystemRow, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, InActive, InVisible, Name, OID, SystemRow, Version From itv913StandardUpgrade..OrgsStatus       
truncate table OrgTypes       
Insert into OrgTypes(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version From itv913StandardUpgrade..OrgTypes       
truncate table Parameters       
Insert into Parameters(Application, Category, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, OID, Value, ValueType, Variable, Version)            Select  Application, Category, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, OID, Value, ValueType, Variable, Version From itv913StandardUpgrade..Parameters       
truncate table PaymentDetail       
Insert into PaymentDetail(Amount, ArDocId, ArTranType, BusId, BusSourceId, Comments, CorCodeId, CreatedBy, CreatedCodeId, CreatedDate, CreatedDiscCodeId, CustId, CustSourceId, DiscAmount, DiscDate, DocDate, EditedBy, EditedDate, ErrorCodeId, ErrorDesc, FoundCodeId, GlAcct, IsCorrected, IsDeleted, IsError, IsReconciled, IsSystemGenerated, MatchingARDocId, MisMatchAmount, MisMatchDiscAmount, OID, OldAmount, OldCustSourceId, OldDiscAmount, OldDocDate, OldPayAmount, OldReasonCode, OldRefNum, PayAmount, PaymentId, PoNum, ReasonCode, ReasonId, RefNum, RmaNum, Source, SourceId, StoreNum, User1, User10, User2, User3, User4, User5, User6, User7, User8, User9, Version)            Select  Amount, ArDocId, ArTranType, BusId, BusSourceId, Comments, CorCodeId, CreatedBy, CreatedCodeId, CreatedDate, CreatedDiscCodeId, CustId, CustSourceId, DiscAmount, DiscDate, DocDate, EditedBy, EditedDate, ErrorCodeId, ErrorDesc, FoundCodeId, GlAcct, IsCorrected, IsDeleted, IsError, IsReconciled, IsSystemGenerated, MatchingARDocId, MisMatchAmount, MisMatchDiscAmount, OID, OldAmount, OldCustSourceId, OldDiscAmount, OldDocDate, OldPayAmount, OldReasonCode, OldRefNum, PayAmount, PaymentId, PoNum, ReasonCode, ReasonId, RefNum, RmaNum, Source, SourceId, StoreNum, User1, User10, User2, User3, User4, User5, User6, User7, User8, User9, Version From itv913StandardUpgrade..PaymentDetail       
truncate table Payments       
Insert into Payments(AccountNum, Amount, ArBatchId, ArTranType, BankSequence, BusId, BusSourceId, CreatedBy, CreatedDate, CustId, CustSourceId, DocDate, EditedBy, EditedDate, ErrorCodeId, ErrorDesc, FileName, IsCorrected, IsDeleted, IsError, IsMerged, IsReconciled, KeyedByName, OID, OldCustSourceId, PaySequence, PostedDate, RefNum, RoutingNum, Source, SourceId, User1, User10, User2, User3, User4, User5, User6, User7, User8, User9, Version)            Select  AccountNum, Amount, ArBatchId, ArTranType, BankSequence, BusId, BusSourceId, CreatedBy, CreatedDate, CustId, CustSourceId, DocDate, EditedBy, EditedDate, ErrorCodeId, ErrorDesc, FileName, IsCorrected, IsDeleted, IsError, IsMerged, IsReconciled, KeyedByName, OID, OldCustSourceId, PaySequence, PostedDate, RefNum, RoutingNum, Source, SourceId, User1, User10, User2, User3, User4, User5, User6, User7, User8, User9, Version From itv913StandardUpgrade..Payments       
truncate table PeriodToPost       
Insert into PeriodToPost(BegDate, ClosingDate, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, EndDate, FinYear, Half, IsClosed, MonthNumber, Name, OID, Period, Quarter, Trimester, Version)            Select  BegDate, ClosingDate, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, EndDate, FinYear, Half, IsClosed, MonthNumber, Name, OID, Period, Quarter, Trimester, Version From itv913StandardUpgrade..PeriodToPost       
truncate table PersonTypes       
Insert into PersonTypes(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version From itv913StandardUpgrade..PersonTypes       
truncate table Persons       
Insert into Persons(Address1, Address2, AddressId, CellPhone, City, Code, Comments, Country, CreatedBy, CreatedDate, DealApprovalLimit, DefaultOrgId, EditedBy, EditedDate, EditPrivilegeNeeded, Email, Fax, FaxExt, FName, HomePhone, InActive, IsAdmin, IsOwner, IsUser, LName, Login, MName, Name, OID, ParentId, Password, PersonType, PromoApprovalLimit, Salutation, Source, SourceId, State, Status, TimeZone, Title, UseCompanyAddress, Version, Workphone, WorkphoneExt, ZipCode)            Select  Address1, Address2, AddressId, CellPhone, City, Code, Comments, Country, CreatedBy, CreatedDate, DealApprovalLimit, DefaultOrgId, EditedBy, EditedDate, EditPrivilegeNeeded, Email, Fax, FaxExt, FName, HomePhone, InActive, IsAdmin, IsOwner, IsUser, LName, Login, MName, Name, OID, ParentId, Password, PersonType, PromoApprovalLimit, Salutation, Source, SourceId, State, Status, TimeZone, Title, UseCompanyAddress, Version, Workphone, WorkphoneExt, ZipCode From itv913StandardUpgrade..Persons       
truncate table Products       
Insert into Products(CompanyId, CreatedBy, CreatedDate, Deleted, Description, EditedBy, EditedDate, EquivCase, EquivLbs, FullPalletCases, GlAcct, HierId, IsGroup, Name, New, NotDealableHigh, NotDealableLow, OID, PackCount, PackSize, ParentId, ProductType, RetailList, ShipWgt, Sku, SlsComm, SortField, Source, SourceCode, SourceId, StdCost, Taxable, UnitMsr, UnitPrice, UpcCode, User1, User2, User3, User4, User5, User6, User7, Version)            Select  CompanyId, CreatedBy, CreatedDate, Deleted, Description, EditedBy, EditedDate, EquivCase, EquivLbs, FullPalletCases, GlAcct, HierId, IsGroup, Name, New, NotDealableHigh, NotDealableLow, OID, PackCount, PackSize, ParentId, ProductType, RetailList, ShipWgt, Sku, SlsComm, SortField, Source, SourceCode, SourceId, StdCost, Taxable, UnitMsr, UnitPrice, UpcCode, User1, User2, User3, User4, User5, User6, User7, Version From itv913StandardUpgrade..Products       
truncate table ProductTypes       
Insert into ProductTypes(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, IsGroup, Name, OID, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, IsGroup, Name, OID, Version From itv913StandardUpgrade..ProductTypes       
truncate table ReasonCodeGroups       
Insert into ReasonCodeGroups(CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version)            Select  CreatedBy, CreatedDate, Description, EditedBy, EditedDate, Name, OID, Version From itv913StandardUpgrade..ReasonCodeGroups       
truncate table ReasonCodes       
Insert into ReasonCodes(ActivityProfileId, ClearAccount, ClearSubAcct, CompanyId, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, GroupId, InActive, InVisible, IsSubReason, Name, OID, ReasonParentId, Source, SourceId, SystemRow, User1, User2, User3, Version)            Select  ActivityProfileId, ClearAccount, ClearSubAcct, CompanyId, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, GroupId, InActive, InVisible, IsSubReason, Name, OID, ReasonParentId, Source, SourceId, SystemRow, User1, User2, User3, Version From itv913StandardUpgrade..ReasonCodes       
truncate table Report       
Insert into Report(ConfigReportMethod, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, FilterScreen, Inactive, Name, OID, ReportFileName, ReportServerCatalog, ReportServerHost, ReportServerPort, Version)            Select  ConfigReportMethod, CreatedBy, CreatedDate, Description, EditedBy, EditedDate, FilterScreen, Inactive, Name, OID, ReportFileName, ReportServerCatalog, ReportServerHost, ReportServerPort, Version From itv913StandardUpgrade..Report       
truncate table ReportHeader       
Insert into ReportHeader(CreatedBy, Createddate, OID, RecordCount, ReportId, Version)            Select  CreatedBy, Createddate, OID, RecordCount, ReportId, Version From itv913StandardUpgrade..ReportHeader       
truncate table ReportXref       
Insert into ReportXref(LinkedId, ReportHeaderId)            Select  LinkedId, ReportHeaderId From itv913StandardUpgrade..ReportXref       
truncate table RollForward       
Insert into RollForward(BalAdjusted, BalAdjuster, BalBegin, BalCurrent, BalEnd, BusId, CreatedBy, CreatedDate, EditedBy, EditedDate, NetChangeCM, NetChangeDD, NetChangeDM, NetChangeIN, NetChangePA, NetDiff, OID, PeriodToPost, Version)            Select  BalAdjusted, BalAdjuster, BalBegin, BalCurrent, BalEnd, BusId, CreatedBy, CreatedDate, EditedBy, EditedDate, NetChangeCM, NetChangeDD, NetChangeDM, NetChangeIN, NetChangePA, NetDiff, OID, PeriodToPost, Version From itv913StandardUpgrade..RollForward       
truncate table Status       
Insert into Status(BaseStatusId, ClosingCmArTranTypeId, ClosingDmArTranTypeId, CreatedBy, CreatedDate, Description, DocState, EditedBy, EditedDate, InSearch, InTickler, InVisible, IsClosed, Name, OID, RequireReason, Source, SourceId, Version)            Select  0, ClosingCmArTranTypeId, ClosingDmArTranTypeId, CreatedBy, CreatedDate, Description, IsClosed, EditedBy, EditedDate, InSearch, InTickler, InVisible, IsClosed, Name, OID, RequireReason, Source, SourceId, Version From itv913StandardUpgrade..Status       
truncate table SyncSteps       
Insert into SyncSteps(ClientDate, CreatedDate, Description, FinishDate, OID, Status, GlBatchId, SyncType, Version)            Select  ClientDate, CreatedDate, Description, FinishDate, OID, Status, SyncBatchId, SyncType, Version From itv913StandardUpgrade..SyncSteps       
truncate table TimeChoices       
Insert into TimeChoices(IntSeconds, TimeAfterChoice, TimeBeforeChoice, TimeChoice)            Select  IntSeconds, TimeAfterChoice, TimeBeforeChoice, TimeChoice From itv913StandardUpgrade..TimeChoices       


Update ArDocs 
SET CarrierSourceId=ARdocsExt.CarrierSourceId 
from itv913StandardUpgrade..ArDocsExt ArDocsExt, ArDocs 
where ArDocsExt.OID=ArDocs.OID



