version: '3.5'
services:
  nine-db:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
      - GRGIT_USER=${GRGIT_USER}
      - CIRCLE_BRANCH=${CIRCLE_BRANCH}
      - PWD=${PWD}
    ports:
      - "3306:3306"
      - "1433:1433"
    volumes:
      - ./:/var/lib/nine-db
