version: '3.5'
services:
  nine-db:
    build:
      context: ./
      dockerfile: Dockerfile
    # depends_on:
    #   - gradle-nine-db
    #   - sqlserver-nine-db
    #   - mysql-nine-db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
      - GRGIT_USER=${GRGIT_USER}
      - CIRCLE_BRANCH=${CIRCLE_BRANCH}
      - PWD=${PWD}
    ports:
      - "3306:3306"
      - "1433:1433"
    volumes:
      - ./:/var/lib/nine-db
  # sqlserver-nine-db:
  #   image: microsoft/mssql-server-linux:2017-CU4
  #   environment:
  #     ACCEPT_EULA: ${ACCEPT_EULA}
  #     SA_PASSWORD: ${SA_PASSWORD}
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - ./sqlserver:/var/lib/sqlserver
    # docker run --name=sqlserver-nine-db \
    # -e ACCEPT_EULA=Y \
    # -e 'SA_PASSWORD=999Foobar' \
    # -d -p 1433:1433 microsoft/mssql-server-linux:2017-CU4

  # mysql-nine-db:
  #   image: mysql/mysql-server:5.7
  #   environment:
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USERNAME: ${MYSQL_USERNAME}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   ports:
  #     - "3306:3306" 
    # docker run --name=mysql-nine-db \
    # -e MYSQL_ROOT_PASSWORD=999Foobar \
    # -e MYSQL_ROOT_HOST=% \
    # -d -p 3306:3306 mysql/mysql-server:5.7

  # gradle-nine-db:
  #   image: dock9/oraclejdk8:gradle-3.5.1
  #   environment:
  #     GRGIT_USER: ${GRGIT_USER}
  #     CIRCLE_BRANCH: ${CIRCLE_BRANCH}
  #   volumes:
  #     - ./gradle:/var/lib/gradle

    # docker run -it --rm --net="host" \
    # --name=gradle-nine-db \
    # -e GRGIT_USER=0305edb725e4e9e308161755e13c0dd50f1d7e9d \
    # -e CIRCLE_BRANCH="release/9.9.x" \
    # -v 123456:/app \
    # dock9/oraclejdk8:gradle-3.5.1 ./ci-scripts/dbcreate.sh test

