# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # 9ci's grails docker with mysql client, this is where all the steps are run
      - image: dock9/oraclejdk8:gradle-3.5.1

      # linked to above, localhost:3606 will see this.
      - image: mysql/mysql-server:5.7
        environment:
          MYSQL_ROOT_PASSWORD: 999Foobar
          MYSQL_ROOT_HOST: '%'
      - image: microsoft/mssql-server-linux:2017-CU4
        environment:
          SA_PASSWORD: 999Foobar
          ACCEPT_EULA: Y

    environment:
      JVM_OPTS: -Xmx3200m
      MALLOC_ARENA_MAX: 2
      #GRADLE_OPTS: "-Xmx2048m -Dorg.gradle.daemon=false"
      TERM: dumb
      MYSQL_SERVER_ADDRESS: 127.0.0.1
      MSSQL_SERVER_ADDRESS: 127.0.0.1

    parallelism: 1
    # resource_class: large

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle buildEnvironment

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - add_ssh_keys:
          fingerprints:
            - "32:15:5c:47:98:e9:3f:09:f9:32:c9:22:00:cc:15:9a"

      # run tests!
      # - run: gradle clean; gradle gorm-tools:check --no-daemon --max-workers 2
      - run: ./ci-scripts/dbcreate.sh test

      # - store_artifacts:
      #     path: plugin/build/reports/tests/test/
      #     destination: test-reports/unit/

      # - store_artifacts:
      #     path: plugin/build/reports/codenarc/
      #     destination: codenarc/ 

      # - store_test_results:
      #     path: plugin/build/test-results

  deploy:
      machine:
        enabled: true
      steps:
        - add_ssh_keys:
            fingerprints:
              - $TARGET_SERVER_SSH_FINGERPRINT
        - run:
            name: Deploy nine-db from docker repository to server
            # Command
            # ./deploy_app.sh \
            #  --docker-user=test \
            #  --docker-password='123qwe!@#QWE' \
            #  --docker-repo=dock9/ocr:latest \
            #  --mysql-repo=mysql/mysql-server:5.7 \
            #  --mssql-repo=microsoft/mssql-server-linux:2017-CU4 \
            #  --gradle-jdk-repo=dock9/oraclejdk8:gradle-3.5.1
            #  --rancher-api-access-key=token-8pv6f \
            #  --rancher-api-secret-key=462fwxgwhw94lsnspqmktdvnsbjr786nhfdwst5h8tlzlsp7tvkf97 \
            #  --rancher-workload-redeployment-api=''

            # Arguments
            # --docker-user: $DOCKERHUB_USER.
            # --docker-password: $DOCKERHUB_PASSWORD
            # --docker-repo: $DOCKER_REPOSITORY:$DOCKER_REPOSITORY_TAG. default dock9/nine-db:latest
            # --mysql-repo=$MYSQL_REPOSITORY
            # --mssql-repo=$MSSQL_REPOSITORY
            # --gradle-jdk-repo=$GRADLE_JDK_REPOSITORY
            # --rancher-api-access-key: $RANCHER_API_ACCESS_KEY
            # --rancher-api-secret-key: $RANCHER_API_SECRET_KEY
            # --rancher-workload-redeployment-api: $RANCHER_WORKLOAD_REDEPLOYMENT_API
            # --rancher-workload-redeployment-api-data: $RANCHER_WORKLOAD_REDEPLOYMENT_API_DATA

            command: |
              ssh -o StrictHostKeyChecking=no \
                $TARGET_SERVER_USER_NAME@$TARGET_SERVER_ADDRESS \
                "/bin/bash ${DEPLOYMENT_SCRIPT_FILE_PATH} --docker-user=${DOCKERHUB_USER} --docker-password=${DOCKERHUB_PASSWORD} --docker-repo=${DOCKER_REPOSITORY}:${DOCKER_REPOSITORY_TAG} --mysql-repo=${MYSQL_REPOSITORY} --mssql-repo=${MSSQL_REPOSITORY} --gradle-jdk-repo=${GRADLE_JDK_REPOSITORY} --circl-branch=${CIRCLE_BRANCH} --rancher-api-access-key=${RANCHER_API_ACCESS_KEY} --rancher-api-secret-key=${RANCHER_API_SECRET_KEY} --rancher-workload-redeployment-api=${RANCHER_WORKLOAD_REDEPLOYMENT_API} --rancher-workload-redeployment-api-data=${RANCHER_WORKLOAD_REDEPLOYMENT_API_DATA}"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - release/9.9.x
